[package]
name = "glob"
version = "1.1.0"
description = "A simple glob pattern matching library"
repository = "https://github.com/edjcase/motoko_glob"
keywords = ["glob", "pattern", "matching", "file", "directory", "path"]
license = "MIT"

[dependencies]
"core@1" = "1.0.0"

[dev-dependencies]
test = "2.1.1"
